name: Generate and upload a release assets

on: push
  # release:
  #   types:
  #     - published
  #     - unpublished
  #     - created
  #     - edited
  #     #- deleted
  #     - prereleased
  #     - released

jobs:
  upload:
    name: Upload Artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: shell-lib/docker/install_docker.sh
      - run: installer/generate_installer.sh
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://github.com/activecm/ACH-Zeek/releases/download/v6.2.2/ACH-Zeek.tar"
          asset_path: installer/ACH-Zeek.tar
          # Note: This will fail if the asset already exists 
          # (e.g. editing a release w/o deleting the existing asset)
          asset_name: ACH-Zeek.tar
          asset_content_type: application/x-tar